plugins {
    `java-library`
    id("xyz.jpenilla.run-paper")
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(25))
    }
    withSourcesJar()
    withJavadocJar()
}

repositories {
    mavenCentral()
    maven("https://repo.papermc.io/repository/maven-public/")
    maven {
        name = "mintGitHubPackages"
        url = uri("https://maven.pkg.github.com/aincraft-org/mint")
        credentials {
            username = providers.gradleProperty("gpr.user")
                .orElse(providers.environmentVariable("GITHUB_ACTOR"))
                .getOrElse("")
            password = providers.gradleProperty("gpr.key")
                .orElse(providers.environmentVariable("GITHUB_TOKEN"))
                .getOrElse("")
        }
    }
}

val mintVersion = "26.8.12.10"
val mintApi = "dev.mintychochip.mint:mint-api:$mintVersion"
val mintPaper = "dev.mintychochip.mint:mint-paper:$mintVersion"

val mintPaperRuntime by configurations.creating {
    isCanBeConsumed = false
    isCanBeResolved = true
}

dependencies {
    api(project(":tradingpost-common"))
    compileOnly("io.papermc.paper:paper-api:26.2.build.111-stable")
    compileOnly(mintApi)
    compileOnly(mintPaper)
    compileOnly("com.zaxxer:HikariCP:6.2.1")
    compileOnly("org.postgresql:postgresql:42.7.5")
    compileOnly("com.mysql:mysql-connector-j:9.3.0")
    compileOnly("org.mariadb.jdbc:mariadb-java-client:3.5.3")
    compileOnly("org.xerial:sqlite-jdbc:3.49.1.0")

    add(mintPaperRuntime.name, mintPaper)

    testImplementation("io.papermc.paper:paper-api:26.2.build.111-stable")
    testImplementation(mintApi)
    testImplementation(mintPaper)
    testImplementation("org.junit.jupiter:junit-jupiter:5.11.4")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher:1.11.4")
}

val mintPaperJarFile: java.io.File =
    mintPaperRuntime.filter { it.name.startsWith("mint-paper-") }.singleFile

val writeMintConfigs = tasks.register("writeMintConfigs") {
    group = "run"
    description = "Write Mint and TradingPost plugin configs for local dev"
    doLast {
        val runDir = layout.projectDirectory.dir("run").asFile
        val mintDir = runDir.resolve("plugins/Mint")
        mintDir.mkdirs()
        mintDir.resolve("config.yml").writeText(
            """
            # Generated by :tradingpost-paper:writeMintConfigs — do not edit; re-run the task.
            runtime:
              admission-capacity: 64
            currency:
              id: mint:credits
              display-name: Credits
              symbol: ¢
              scale: 2
              active: true
              policies: []
            database:
              enabled: true
              jdbc-url: jdbc:postgresql://localhost:5432/mint
              username: mint
              password: mint
              pool-size: 10
              connection-timeout-ms: 5000
              soft-mode: false
              check-durable-on-accept: false
              microbatch-max: 64
              queue-capacity: 1024
              flush-interval-ms: 50
              lanes: 4
            integrations:
              policy-providers: []
              vault-plugin: MintVaultBridge
              profiles:
              - plugin: TradingPost
                profile-id: profile:tradingpost
                revision: 1
                client-id: tradingpost:plugin
                actor-id: tradingpost:plugin
                actions: [ACCOUNT_CREATE, ACCOUNT_READ, BALANCE_READ, CURRENCY_READ, TRANSFER, RECEIPT_READ]
                account-scopes:
                - kind: NAMESPACE
                  namespace: player
                  access: [CREATE, READ, DEBIT, CREDIT]
                - kind: EXACT
                  account: tradingpost:escrow
                  access: [CREATE, READ, DEBIT, CREDIT]
                - kind: EXACT
                  account: tradingpost:fees
                  access: [CREATE, READ, DEBIT, CREDIT]
                - kind: EXACT
                  account: tradingpost:tax
                  access: [CREATE, READ, DEBIT, CREDIT]
                currency-scopes:
                - kind: EXACT
                  currency: mint:credits
                  access: [READ, USE]
                providers: []
                hold-control: NONE
                quote-control: NONE
                schedule-control: NONE
                max-in-flight: 16
            exchange:
              pairs: []
            """.trimIndent() + "\n",
        )

        val tradingPostDir = runDir.resolve("plugins/TradingPost")
        tradingPostDir.mkdirs()
        val tradingPostConfig = tradingPostDir.resolve("config.yml")
        if (!tradingPostConfig.isFile) {
            tradingPostConfig.writeText(
                project(":tradingpost-paper").file("src/main/resources/config.yml").readText()
                    .replace("password: change-me", "password: mint"),
            )
        } else {
            tradingPostConfig.writeText(
                tradingPostConfig.readText().replace("password: change-me", "password: mint"),
            )
        }
    }
}

tasks.named<xyz.jpenilla.runpaper.task.RunServer>("runServer") {
    minecraftVersion("26.2")
    runDirectory.set(layout.projectDirectory.dir("run"))
    pluginJars(
        tasks.jar.flatMap { it.archiveFile },
        project(":tradingpost-test").tasks.named<Jar>("jar").flatMap { it.archiveFile },
        mintPaperJarFile,
    )
    dependsOn(
        tasks.jar,
        project(":tradingpost-test").tasks.named("jar"),
        writeMintConfigs,
    )
}

tasks.withType<JavaCompile>().configureEach {
    options.release.set(25)
    options.encoding = "UTF-8"
}

tasks.test {
    useJUnitPlatform()
    maxParallelForks = 1
    reports.junitXml.required.set(false)
}

tasks.jar {
    archiveBaseName.set("tradingpost-paper")
    archiveVersion.set("")
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from(
        project(":tradingpost-common").tasks.named("jar").map { zipTree(it.outputs.files.singleFile) },
    )
    from(
        project(":tradingpost-api").tasks.named("jar").map { zipTree(it.outputs.files.singleFile) },
    )
}
